// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: proto/presence_service.proto

package presence

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_presence_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_presence_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_presence_service_proto_rawDescGZIP(), []int{0}
}

func (x *StatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	LastSeen      string                 `protobuf:"bytes,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_presence_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_presence_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_presence_service_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

var File_proto_presence_service_proto protoreflect.FileDescriptor

const file_proto_presence_service_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/presence_service.proto\x12\bpresence\"(\n" +
	"\rStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"^\n" +
	"\x0eStatusResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\tR\blastSeen2Q\n" +
	"\x0fPresenceService\x12>\n" +
	"\tGetStatus\x12\x17.presence.StatusRequest\x1a\x18.presence.StatusResponseB;Z9github.com/bottomhalf/btc-grpc-presence/genproto/presenceb\x06proto3"

var (
	file_proto_presence_service_proto_rawDescOnce sync.Once
	file_proto_presence_service_proto_rawDescData []byte
)

func file_proto_presence_service_proto_rawDescGZIP() []byte {
	file_proto_presence_service_proto_rawDescOnce.Do(func() {
		file_proto_presence_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_presence_service_proto_rawDesc), len(file_proto_presence_service_proto_rawDesc)))
	})
	return file_proto_presence_service_proto_rawDescData
}

var file_proto_presence_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_presence_service_proto_goTypes = []any{
	(*StatusRequest)(nil),  // 0: presence.StatusRequest
	(*StatusResponse)(nil), // 1: presence.StatusResponse
}
var file_proto_presence_service_proto_depIdxs = []int32{
	0, // 0: presence.PresenceService.GetStatus:input_type -> presence.StatusRequest
	1, // 1: presence.PresenceService.GetStatus:output_type -> presence.StatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_presence_service_proto_init() }
func file_proto_presence_service_proto_init() {
	if File_proto_presence_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_presence_service_proto_rawDesc), len(file_proto_presence_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_presence_service_proto_goTypes,
		DependencyIndexes: file_proto_presence_service_proto_depIdxs,
		MessageInfos:      file_proto_presence_service_proto_msgTypes,
	}.Build()
	File_proto_presence_service_proto = out.File
	file_proto_presence_service_proto_goTypes = nil
	file_proto_presence_service_proto_depIdxs = nil
}
